server {
    listen 80;
    # Set the root to the parent folder
    root /usr/share/nginx/html;

    # Matches both /spa and /spa/
    location /spa {
        index index.html;
        # This is the magic for React Router + Vite Base path
        try_files $uri $uri/ /spa/index.html;
    }

    # Optional: redirect empty root to /spa/
    location = / {
        return 301 /spa/;
    }
}
