server {
    listen 80;

    location /spa/ { # <--- Change this to /spa/
        alias /usr/share/nginx/html/; # Use alias instead of root
        index index.html;
        try_files $uri $uri/ /spa/index.html;
    }

    # Redirect root to /spa/ (Optional)
    location = / {
        return 301 /spa/;
    }
}